language: dart

dart:
  - dev

jobs:
  include:
    - stage: test
      name: "vm tests"
      dart: be/raw/latest
      os: linux
      script: pub run --enable-experiment=non-nullable test -p vm

stages:
  - test

branches:
  only: [master, null_safety]

cache:
  directories:
    - $HOME/.pub-cache
