analyzer:
  exclude:
    - example/**
  # strong-mode:
  #   implicit-casts: false
  #   implicit-dynamic: false
linter:
  rules:
    - annotate_overrides
    - cancel_subscriptions
    - hash_and_equals
    - iterable_contains_unrelated_type
    - lines_longer_than_80_chars
    - list_remove_unrelated_type
    - omit_local_variable_types
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_mixin
    - test_types_in_equals
    - unnecessary_const
    - unnecessary_lambdas
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_this
    - unrelated_type_equality_checks
    - valid_regexps
