name: jinja
description: >-
  Jinja2 server-side template engine for Dart.
  Variables, expressions, control structures and template inheritance.
homepage: https://github.com/ykmnkmi/jinja.dart
version: 0.4.0-dev.15

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  path: ^1.8.0
  quiver: ^3.0.0
  string_scanner: ^1.1.0
  textwrap: ^1.0.0

dev_dependencies:
  benchmark_harness: ^2.0.0
  build_runner: ^2.1.0
  build_web_compilers: ^3.2.0
  lints: ^1.0.0
  test: ^1.17.0
