name: jinja
description: >-
  Jinja2 server-side template engine for Dart.
  Variables, expressions, control structures and template inheritance.
version: 0.1.1
homepage: https://github.com/ykmnkmi/dart-jinja
author: Suleimen Olzhas <amajisenpai@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  meta: ^1.1.7
  path: ^1.6.2
  string_scanner: ^1.0.4

dev_dependencies:
  test: ^1.5.3
