name: jinja
description: >-
  Jinja2 server-side template engine for Dart.
  Variables, expressions, control structures and template inheritance.
version: 0.3.0-dev+7
homepage: https://github.com/ykmnkmi/jinja.dart

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  path: ^1.8.0-nullsafety
  string_scanner: ^1.1.0-nullsafety

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
